[variables]
NODE_ENV = "production"
NIXPACKS_NODE_VERSION = "20"

[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = [
  "npm ci --no-audit --no-fund", 
  "cd webapp && npm ci --no-audit --no-fund"
]

[phases.build]
cmds = [
  "npm run build"
]

[start]
cmd = "node dist/server.js" 