[variables]
NODE_VERSION = "20"
PACKAGE_MANAGER = "npm"

[phases.setup]
nixPkgs = ["nodejs_20", "npm-9_x"]

[phases.install]
cmds = ["npm install --no-audit --no-fund"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "node dist/server.js" 