[nixpacks]
plan = "node"

[variables]
BP_NODE_VERSION = "20"
NPM_CONFIG_LEGACY_PEER_DEPS = "true"

[phases.install]
cmds = ["npm ci --no-audit --no-fund"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "node dist/server.js" 