[nixpacks]
plan = "node"

[variables]
BP_NODE_VERSION = "20"
NODE_ENV = "production"

[phases.install]
cmds = [
  "npm ci --no-audit --no-fund", 
  "cd webapp && npm ci --no-audit --no-fund"
]

[phases.build]
cmds = [
  "npm run build",
  "cd webapp && npm run build"
]

[start]
cmd = "node dist/server.js" 