name: CI + Deploy
on:
  push:
    branches: [main]
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: 20 }
      - run: npm ci
      - run: npm run lint --silent
      - run: npx tsc --noEmit
      - run: npm test --silent
      - name: docker build test
        uses: docker/build-push-action@v5
        with:
          context: .
          load: false
          push: false
  deploy:
    needs: ci
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: superfly/flyctl-actions@1.5
        with:
          args: "deploy --remote-only"
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
